print("""1. triple-quoted strings can span multiple lines, whereas single or double quotes can only use one line""")
print()
print("""2. Function specifications are useful because they allow someone to best use the function without needing in-depth knowledge to how it works""")
print()
print("""3. You should include the meanings of the parameters, the function's effects, return value(s) and type, as well as any pre and post conditions.""")
print()
print("""4. They go in docstrings that are right under the header of the function""")
print()
print("""5. It is the fault of the user, as the program specifies the parameters must be numbers.""")
print()
print("""6. It is the fault of the function, as the preconditions were all met, yet the postconditions were incorrect.""")